---
- name: Install htop
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install htop
      ansible.builtin.apt:
        name: htop
        state: present
